### ISSUE TITLE
Move the list sharing form to home page.

### ISSUE THREAD

**Issue by Hudamabkhoot** [the-collab-lab/tcl-79-smart-shopping-list#32]
- Adding a delete button to each list.
- Moving the list sharing to home page and add it next to the delete button.
- When a user clicks on the share button a modal with the `Invite a user by email` form is displayed. 
- Clicking on a list name should direct the user to that list's page.

**Comment by redapy** [comment]
> Adding a delete button to each list.

It could be complicated, better left to the end
